controllers/ExtractorController.php
<?php
/**
 *
 */

namespace app\controllers;


use app\forms\RequestForm;
use app\models\Taxpayer;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Class ExtractorController
 *
 * @package app\controllers
 */
class ExtractorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'search' => ['post'],
                ],
            ],
        ];
    }

    /**
     *
     */
    public function actionIndex()
    {
        $taxpayerDataProvider = new ActiveDataProvider([
            'query' => Taxpayer::find(),
        ]);

        return $this->render('index', [
            'taxpayerDataProvider' => $taxpayerDataProvider,
            'requestForm'          => \Yii::createObject(RequestForm::class),
        ]);
    }

    /**
     * @param string $id IIN
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $iin = $id;

        $taxpayer = Taxpayer::findOne(['iin' => $iin]);
        if ( ! $taxpayer) {
            throw new NotFoundHttpException('Taxpayer not found');
        }

        return $this->render('view', [
            'taxpayer' => $taxpayer,
        ]);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionSearch()
    {
        $requestForm = \Yii::createObject(RequestForm::class);
        $requestForm->load(\Yii::$app->request->post());

        $data = \Yii::$app->extractor->pull($requestForm->iin);

        \Yii::$app->extractor->dump($data)
            ? \Yii::$app->session->addFlash('success', 'Success')
            : \Yii::$app->session->addFlash('error', 'Something went wrong');

        return $this->redirect('index');
    }
}

views/extractor/index.php
<?php
/**
 * @var \app\forms\RequestForm          $requestForm
 * @var \yii\data\DataProviderInterface $taxpayerDataProvider
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

?>
<div class="extractor-index">
    <?php
    $form = ActiveForm::begin([
        'id'     => 'search-form',
        'method' => 'post',
        'action' => \yii\helpers\Url::toRoute('extractor/search'),
    ]) ?>
    <?= $form->field($requestForm, 'iin') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end() ?>

    <?= \yii\grid\GridView::widget([
        'dataProvider' => $taxpayerDataProvider,
        'columns'      => [
            [
                'class' => \yii\grid\SerialColumn::class,
            ],
            'iin',
            'name',
            'total_arrear',
            'total_pension_contribution_arrear',
            'total_social_contribution_arrear',
//            'created_at:datetime',
//            'updated_at:datetime',
            [
                'class'    => \yii\grid\ActionColumn::class,
                'template' => '{view}',
            ],
        ],
    ]) ?>
</div>

views/extractor/view.php
<?php
/**
 * @var \app\models\Taxpayer $taxpayer
 */
?>
<div class="extractor-view">
    <?= \yii\bootstrap\Html::a('List', ['index'], ['class' => 'btn btn-success']) ?>
    <hr>
    <?= \yii\widgets\DetailView::widget([
        'model' => $taxpayer,
    ]) ?>
    <hr>
    <?= \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query'   => $taxpayer->getTaxInfos(),
        ]),
        'columns' => [
            'agencyCode',
            'arrearTypeCode',
            'bcc_tax_arrear',
            'bcc_poena_arrear',
            'bcc_fine_arrear',
            'bcc_total_arrear',
        ],
    ]) ?>
</div>